application: david-misshula
version: 1
runtime: python
api_version: 1

handlers:
    
- url: /css
  static_dir: css

- url: /images
  static_dir: images 

- url: /pdf
  static_dir: pdf 

- url: /js
  static_dir: js

- url: .*
  script: main.py